name: Build and push to AWS

on:
  push:
    branches:
      - main
      - webAPI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0'

      - name: Build project
        run: dotnet restore; dotnet publish ./safeLockr/safeLockr.csproj -o safeLockr;

      - name: Create zip package
        run: cd safeLockr; zip ../safeLockr.zip *;

      - name: Deploy to AWS EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: safeLockrAPI
          environment_name: safeLockrAPI-env
          version_label: ${{ github.run_id }}
          region: eu-north-1
          deployment_package: safeLockr.zip